name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm ci && npm run build
        env:
          NODE_VERSION: 18

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: af0faebfb1b3ae4956ecdd9927fa1f87
          projectName: bookshelf-ai
          directory: dist # This should be the build output directory
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }} # Optional
          # branch: main # Optional
